# DO NOT DELETE: Beginning of Haskell dependencies
hssqlppp-pg/src/Database/HsSqlPpp/Utils/Here2.o : hssqlppp-pg/src/Database/HsSqlPpp/Utils/Here2.lhs
hssqlppp/tests/Database/HsSqlPpp/Utils/GroomUtils.o : hssqlppp/tests/Database/HsSqlPpp/Utils/GroomUtils.lhs
hssqlppp/src/Database/HsSqlPpp/Parsing/ParseErrors.o : hssqlppp/src/Database/HsSqlPpp/Parsing/ParseErrors.lhs
hssqlppp/src/Database/HsSqlPpp/Utils/Utils.o : hssqlppp/src/Database/HsSqlPpp/Utils/Utils.lhs
hssqlppp-pg/src/Database/HsSqlPpp/Utils/PgUtils.o : hssqlppp-pg/src/Database/HsSqlPpp/Utils/PgUtils.lhs
hssqlppp/tests/Database/HsSqlPpp/Utils/Here.o : hssqlppp/tests/Database/HsSqlPpp/Utils/Here.lhs
hssqlppp/src/Database/HsSqlPpp/Internals/TypesInternal.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypesInternal.lhs
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o : hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.lhs
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypesInternal.hi
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o : hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.lhs
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o : hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTSQLCatalog.o : hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTSQLCatalog.lhs
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTSQLCatalog.o : hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.hi
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTSQLCatalog.o : hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
hssqlppp/src/Database/HsSqlPpp/Catalog.o : hssqlppp/src/Database/HsSqlPpp/Catalog.lhs
hssqlppp/src/Database/HsSqlPpp/Catalog.o : hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTSQLCatalog.hi
hssqlppp/src/Database/HsSqlPpp/Catalog.o : hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.hi
hssqlppp/src/Database/HsSqlPpp/Catalog.o : hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
hssqlppp-pg/src/Database/HsSqlPpp/Utils/CatalogReader.o : hssqlppp-pg/src/Database/HsSqlPpp/Utils/CatalogReader.lhs
hssqlppp-pg/src/Database/HsSqlPpp/Utils/CatalogReader.o : hssqlppp-pg/src/Database/HsSqlPpp/Utils/PgUtils.hi
hssqlppp-pg/src/Database/HsSqlPpp/Utils/CatalogReader.o : hssqlppp/src/Database/HsSqlPpp/Catalog.hi
hssqlppp-pg/src/Database/HsSqlPpp/Utils/CatalogReader.o : hssqlppp-pg/src/Database/HsSqlPpp/Utils/Here2.hi
src-extra/devel-util/MakeDefaultTemplate1Catalog.o : src-extra/devel-util/MakeDefaultTemplate1Catalog.lhs
src-extra/devel-util/MakeDefaultTemplate1Catalog.o : hssqlppp-pg/src/Database/HsSqlPpp/Utils/PgUtils.hi
src-extra/devel-util/MakeDefaultTemplate1Catalog.o : hssqlppp-pg/src/Database/HsSqlPpp/Utils/CatalogReader.hi
src-extra/devel-util/MakeDefaultTemplate1Catalog.o : hssqlppp/tests/Database/HsSqlPpp/Utils/Here.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TpchData.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TpchData.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/TpchData.o : hssqlppp/src/Database/HsSqlPpp/Catalog.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TpchData.o : hssqlppp/tests/Database/HsSqlPpp/Utils/Here.hi
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/OldTediousTypeUtils.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/OldTediousTypeUtils.lhs
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/OldTediousTypeUtils.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypesInternal.hi
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.lhs
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/OldTediousTypeUtils.hi
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.o : hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypesInternal.hi
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/SqlTypeConversion.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/SqlTypeConversion.lhs
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/SqlTypeConversion.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.hi
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/SqlTypeConversion.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/OldTediousTypeUtils.hi
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/SqlTypeConversion.o : hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/SqlTypeConversion.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypesInternal.hi
hssqlppp/src/Database/HsSqlPpp/Types.o : hssqlppp/src/Database/HsSqlPpp/Types.lhs
hssqlppp/src/Database/HsSqlPpp/Types.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypesInternal.hi
hssqlppp/src/Database/HsSqlPpp/SqlDialect.o : hssqlppp/src/Database/HsSqlPpp/SqlDialect.lhs
hssqlppp/src/Database/HsSqlPpp/Parsing/Lexer.o : hssqlppp/src/Database/HsSqlPpp/Parsing/Lexer.lhs
hssqlppp/src/Database/HsSqlPpp/Parsing/Lexer.o : hssqlppp/src/Database/HsSqlPpp/SqlDialect.hi
hssqlppp/src/Database/HsSqlPpp/Parsing/Lexer.o : hssqlppp/src/Database/HsSqlPpp/Utils/Utils.hi
hssqlppp/src/Database/HsSqlPpp/Parsing/Lexer.o : hssqlppp/src/Database/HsSqlPpp/Parsing/ParseErrors.hi
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.lhs
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/SqlTypeConversion.hi
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o : hssqlppp/src/Database/HsSqlPpp/SqlDialect.hi
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.hi
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o : hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypesInternal.hi
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/Environment.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/Environment.lhs
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/Environment.o : hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/Environment.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.hi
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/Environment.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypesInternal.hi
hssqlppp/src/Database/HsSqlPpp/Internals/AstInternal.o : hssqlppp/src/Database/HsSqlPpp/Internals/AstInternal.hs
hssqlppp/src/Database/HsSqlPpp/Internals/AstInternal.o : hssqlppp/src/Database/HsSqlPpp/SqlDialect.hi
hssqlppp/src/Database/HsSqlPpp/Internals/AstInternal.o : hssqlppp/src/Database/HsSqlPpp/Utils/Utils.hi
hssqlppp/src/Database/HsSqlPpp/Internals/AstInternal.o : hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
hssqlppp/src/Database/HsSqlPpp/Internals/AstInternal.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/Environment.hi
hssqlppp/src/Database/HsSqlPpp/Internals/AstInternal.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.hi
hssqlppp/src/Database/HsSqlPpp/Internals/AstInternal.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypesInternal.hi
hssqlppp/src/Database/HsSqlPpp/TypeChecker.o : hssqlppp/src/Database/HsSqlPpp/TypeChecker.lhs
hssqlppp/src/Database/HsSqlPpp/TypeChecker.o : hssqlppp/src/Database/HsSqlPpp/SqlDialect.hi
hssqlppp/src/Database/HsSqlPpp/TypeChecker.o : hssqlppp/src/Database/HsSqlPpp/Internals/AstInternal.hi
hssqlppp/src/Database/HsSqlPpp/Annotation.o : hssqlppp/src/Database/HsSqlPpp/Annotation.lhs
hssqlppp/src/Database/HsSqlPpp/Annotation.o : hssqlppp/src/Database/HsSqlPpp/Internals/AstInternal.hi
hssqlppp/src/Database/HsSqlPpp/Ast.o : hssqlppp/src/Database/HsSqlPpp/Ast.lhs
hssqlppp/src/Database/HsSqlPpp/Ast.o : hssqlppp/src/Database/HsSqlPpp/Internals/AstInternal.hi
hssqlppp/src/Database/HsSqlPpp/Parsing/ParserInternal.o : hssqlppp/src/Database/HsSqlPpp/Parsing/ParserInternal.lhs
hssqlppp/src/Database/HsSqlPpp/Parsing/ParserInternal.o : hssqlppp/src/Database/HsSqlPpp/SqlDialect.hi
hssqlppp/src/Database/HsSqlPpp/Parsing/ParserInternal.o : hssqlppp/src/Database/HsSqlPpp/Utils/Utils.hi
hssqlppp/src/Database/HsSqlPpp/Parsing/ParserInternal.o : hssqlppp/src/Database/HsSqlPpp/Annotation.hi
hssqlppp/src/Database/HsSqlPpp/Parsing/ParserInternal.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/src/Database/HsSqlPpp/Parsing/ParserInternal.o : hssqlppp/src/Database/HsSqlPpp/Parsing/ParseErrors.hi
hssqlppp/src/Database/HsSqlPpp/Parsing/ParserInternal.o : hssqlppp/src/Database/HsSqlPpp/Parsing/Lexer.hi
hssqlppp/src/Database/HsSqlPpp/Parser.o : hssqlppp/src/Database/HsSqlPpp/Parser.lhs
hssqlppp/src/Database/HsSqlPpp/Parser.o : hssqlppp/src/Database/HsSqlPpp/Parsing/ParserInternal.hi
hssqlppp/src/Database/HsSqlPpp/Utility.o : hssqlppp/src/Database/HsSqlPpp/Utility.lhs
hssqlppp/src/Database/HsSqlPpp/Utility.o : hssqlppp/src/Database/HsSqlPpp/Parser.hi
hssqlppp/src/Database/HsSqlPpp/Utility.o : hssqlppp/src/Database/HsSqlPpp/Catalog.hi
hssqlppp/src/Database/HsSqlPpp/Utility.o : hssqlppp/src/Database/HsSqlPpp/Parsing/Lexer.hi
hssqlppp/src/Database/HsSqlPpp/Utility.o : hssqlppp/src/Database/HsSqlPpp/Internals/TypesInternal.hi
hssqlppp/src/Database/HsSqlPpp/Utility.o : hssqlppp/src/Database/HsSqlPpp/Internals/AstInternal.hi
hssqlppp-th/src/Database/HsSqlPpp/Quote.o : hssqlppp-th/src/Database/HsSqlPpp/Quote.lhs
hssqlppp-th/src/Database/HsSqlPpp/Quote.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp-th/src/Database/HsSqlPpp/Quote.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp-th/src/Database/HsSqlPpp/Quote.o : hssqlppp/src/Database/HsSqlPpp/Annotation.hi
hssqlppp-th/src/Database/HsSqlPpp/Quote.o : hssqlppp/src/Database/HsSqlPpp/Parser.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.o : hssqlppp/src/Database/HsSqlPpp/Annotation.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.o : hssqlppp/tests/Database/HsSqlPpp/Utils/Here.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.o : hssqlppp/tests/Database/HsSqlPpp/Utils/Here.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Joins.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Joins.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Joins.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Joins.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Dml.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Dml.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Dml.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Dml.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Misc.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Misc.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Misc.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Misc.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/src/Database/HsSqlPpp/Pretty.o : hssqlppp/src/Database/HsSqlPpp/Pretty.lhs
hssqlppp/src/Database/HsSqlPpp/Pretty.o : hssqlppp/src/Database/HsSqlPpp/SqlDialect.hi
hssqlppp/src/Database/HsSqlPpp/Pretty.o : hssqlppp/src/Database/HsSqlPpp/Annotation.hi
hssqlppp/src/Database/HsSqlPpp/Pretty.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Misc.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Dml.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Joins.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/tests/Database/HsSqlPpp/Utils/GroomUtils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/src/Database/HsSqlPpp/Utility.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/src/Database/HsSqlPpp/Pretty.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/src/Database/HsSqlPpp/Parser.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : hssqlppp/src/Database/HsSqlPpp/Utility.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : hssqlppp-th/src/Database/HsSqlPpp/Quote.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : hssqlppp/src/Database/HsSqlPpp/Pretty.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : hssqlppp/src/Database/HsSqlPpp/Annotation.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : hssqlppp/src/Database/HsSqlPpp/Ast.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : hssqlppp/tests/Database/HsSqlPpp/Utils/GroomUtils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : hssqlppp/src/Database/HsSqlPpp/Utility.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : hssqlppp/src/Database/HsSqlPpp/Pretty.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : hssqlppp/src/Database/HsSqlPpp/Types.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : hssqlppp/src/Database/HsSqlPpp/Catalog.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : hssqlppp/src/Database/HsSqlPpp/Annotation.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : hssqlppp/src/Database/HsSqlPpp/TypeChecker.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : hssqlppp/src/Database/HsSqlPpp/Parser.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.o : hssqlppp/src/Database/HsSqlPpp/Types.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.o : hssqlppp/src/Database/HsSqlPpp/Catalog.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.o : hssqlppp/src/Database/HsSqlPpp/Types.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.o : hssqlppp/src/Database/HsSqlPpp/TypeChecker.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.o : hssqlppp/src/Database/HsSqlPpp/Catalog.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o : hssqlppp/src/Database/HsSqlPpp/Catalog.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o : hssqlppp/src/Database/HsSqlPpp/Types.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TpchData.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.o : hssqlppp/src/Database/HsSqlPpp/Types.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.o : hssqlppp/src/Database/HsSqlPpp/Catalog.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.o : hssqlppp/src/Database/HsSqlPpp/Types.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.o : hssqlppp/src/Database/HsSqlPpp/Types.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.o : hssqlppp/src/Database/HsSqlPpp/TypeChecker.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TSQL.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TSQL.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TSQL.o : hssqlppp/src/Database/HsSqlPpp/Catalog.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TSQL.o : hssqlppp/src/Database/HsSqlPpp/Types.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TSQL.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Issues.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Issues.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Issues.o : hssqlppp/src/Database/HsSqlPpp/Catalog.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Issues.o : hssqlppp/src/Database/HsSqlPpp/TypeChecker.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Issues.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Issues.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TSQL.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Tests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Tests.lhs
hssqlppp/tests/Database/HsSqlPpp/Tests/Tests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Tests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.hi
hssqlppp/tests/Database/HsSqlPpp/Tests/Tests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.hi
hssqlppp/tests/Tests.o : hssqlppp/tests/Tests.lhs
hssqlppp/tests/Tests.o : hssqlppp/tests/Database/HsSqlPpp/Tests/Tests.hi
# DO NOT DELETE: End of Haskell dependencies
