# DO NOT DELETE: Beginning of Haskell dependencies
src-extra/utils/Database/HsSqlPpp/Utils/Here.o : src-extra/utils/Database/HsSqlPpp/Utils/Here.lhs
src-extra/tests/Database/HsSqlPpp/Utils/GroomUtils.o : src-extra/tests/Database/HsSqlPpp/Utils/GroomUtils.lhs
src/Database/HsSqlPpp/Parsing/ParseErrors.o : src/Database/HsSqlPpp/Parsing/ParseErrors.lhs
src/Database/HsSqlPpp/Utils/Utils.o : src/Database/HsSqlPpp/Utils/Utils.lhs
src/Database/HsSqlPpp/Internals/TypesInternal.o : src/Database/HsSqlPpp/Internals/TypesInternal.lhs
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.lhs
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o : src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.lhs
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
src/Database/HsSqlPpp/Internals/Catalog/DefaultTSQLCatalog.o : src/Database/HsSqlPpp/Internals/Catalog/DefaultTSQLCatalog.lhs
src/Database/HsSqlPpp/Internals/Catalog/DefaultTSQLCatalog.o : src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.hi
src/Database/HsSqlPpp/Internals/Catalog/DefaultTSQLCatalog.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
src/Database/HsSqlPpp/Catalog.o : src/Database/HsSqlPpp/Catalog.lhs
src/Database/HsSqlPpp/Catalog.o : src/Database/HsSqlPpp/Internals/Catalog/DefaultTSQLCatalog.hi
src/Database/HsSqlPpp/Catalog.o : src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.hi
src/Database/HsSqlPpp/Catalog.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
src-extra/tests/Database/HsSqlPpp/Tests/TpchData.o : src-extra/tests/Database/HsSqlPpp/Tests/TpchData.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TpchData.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/tests/Database/HsSqlPpp/Tests/TpchData.o : src-extra/utils/Database/HsSqlPpp/Utils/Here.hi
src/Database/HsSqlPpp/Internals/TypeChecking/OldTediousTypeUtils.o : src/Database/HsSqlPpp/Internals/TypeChecking/OldTediousTypeUtils.lhs
src/Database/HsSqlPpp/Internals/TypeChecking/OldTediousTypeUtils.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.o : src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.lhs
src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.o : src/Database/HsSqlPpp/Internals/TypeChecking/OldTediousTypeUtils.hi
src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/Internals/TypeChecking/SqlTypeConversion.o : src/Database/HsSqlPpp/Internals/TypeChecking/SqlTypeConversion.lhs
src/Database/HsSqlPpp/Internals/TypeChecking/SqlTypeConversion.o : src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.hi
src/Database/HsSqlPpp/Internals/TypeChecking/SqlTypeConversion.o : src/Database/HsSqlPpp/Internals/TypeChecking/OldTediousTypeUtils.hi
src/Database/HsSqlPpp/Internals/TypeChecking/SqlTypeConversion.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
src/Database/HsSqlPpp/Internals/TypeChecking/SqlTypeConversion.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/Types.o : src/Database/HsSqlPpp/Types.lhs
src/Database/HsSqlPpp/Types.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/Internals/StringLike.o : src/Database/HsSqlPpp/Internals/StringLike.lhs
src/Database/HsSqlPpp/SqlDialect.o : src/Database/HsSqlPpp/SqlDialect.lhs
src/Database/HsSqlPpp/Parsing/Lexer.o : src/Database/HsSqlPpp/Parsing/Lexer.lhs
src/Database/HsSqlPpp/Parsing/Lexer.o : src/Database/HsSqlPpp/SqlDialect.hi
src/Database/HsSqlPpp/Parsing/Lexer.o : src/Database/HsSqlPpp/Utils/Utils.hi
src/Database/HsSqlPpp/Parsing/Lexer.o : src/Database/HsSqlPpp/Parsing/ParseErrors.hi
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o : src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.lhs
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o : src/Database/HsSqlPpp/Internals/TypeChecking/SqlTypeConversion.hi
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o : src/Database/HsSqlPpp/SqlDialect.hi
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o : src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.hi
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/Internals/TypeChecking/Environment.o : src/Database/HsSqlPpp/Internals/TypeChecking/Environment.lhs
src/Database/HsSqlPpp/Internals/TypeChecking/Environment.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
src/Database/HsSqlPpp/Internals/TypeChecking/Environment.o : src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.hi
src/Database/HsSqlPpp/Internals/TypeChecking/Environment.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/Internals/AstInternal.o : src/Database/HsSqlPpp/Internals/AstInternal.hs
src/Database/HsSqlPpp/Internals/AstInternal.o : src/Database/HsSqlPpp/SqlDialect.hi
src/Database/HsSqlPpp/Internals/AstInternal.o : src/Database/HsSqlPpp/Utils/Utils.hi
src/Database/HsSqlPpp/Internals/AstInternal.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
src/Database/HsSqlPpp/Internals/AstInternal.o : src/Database/HsSqlPpp/Internals/TypeChecking/Environment.hi
src/Database/HsSqlPpp/Internals/AstInternal.o : src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.hi
src/Database/HsSqlPpp/Internals/AstInternal.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/TypeChecker.o : src/Database/HsSqlPpp/TypeChecker.lhs
src/Database/HsSqlPpp/TypeChecker.o : src/Database/HsSqlPpp/SqlDialect.hi
src/Database/HsSqlPpp/TypeChecker.o : src/Database/HsSqlPpp/Internals/AstInternal.hi
src/Database/HsSqlPpp/Annotation.o : src/Database/HsSqlPpp/Annotation.lhs
src/Database/HsSqlPpp/Annotation.o : src/Database/HsSqlPpp/Internals/AstInternal.hi
src-extra/tests/Database/HsSqlPpp/Tests/TestUtils.o : src-extra/tests/Database/HsSqlPpp/Tests/TestUtils.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TestUtils.o : src/Database/HsSqlPpp/Annotation.hi
src/Database/HsSqlPpp/Ast.o : src/Database/HsSqlPpp/Ast.lhs
src/Database/HsSqlPpp/Ast.o : src/Database/HsSqlPpp/Internals/AstInternal.hi
src/Database/HsSqlPpp/Parsing/ParserInternal.o : src/Database/HsSqlPpp/Parsing/ParserInternal.lhs
src/Database/HsSqlPpp/Parsing/ParserInternal.o : src/Database/HsSqlPpp/SqlDialect.hi
src/Database/HsSqlPpp/Parsing/ParserInternal.o : src/Database/HsSqlPpp/Utils/Utils.hi
src/Database/HsSqlPpp/Parsing/ParserInternal.o : src/Database/HsSqlPpp/Annotation.hi
src/Database/HsSqlPpp/Parsing/ParserInternal.o : src/Database/HsSqlPpp/Ast.hi
src/Database/HsSqlPpp/Parsing/ParserInternal.o : src/Database/HsSqlPpp/Parsing/ParseErrors.hi
src/Database/HsSqlPpp/Parsing/ParserInternal.o : src/Database/HsSqlPpp/Parsing/Lexer.hi
src/Database/HsSqlPpp/Quote.o : src/Database/HsSqlPpp/Quote.lhs
src/Database/HsSqlPpp/Quote.o : src/Database/HsSqlPpp/Ast.hi
src/Database/HsSqlPpp/Quote.o : src/Database/HsSqlPpp/Ast.hi
src/Database/HsSqlPpp/Quote.o : src/Database/HsSqlPpp/Annotation.hi
src/Database/HsSqlPpp/Quote.o : src/Database/HsSqlPpp/Parsing/ParserInternal.hi
src/Database/HsSqlPpp/Parser.o : src/Database/HsSqlPpp/Parser.lhs
src/Database/HsSqlPpp/Parser.o : src/Database/HsSqlPpp/Parsing/ParserInternal.hi
src/Database/HsSqlPpp/Utility.o : src/Database/HsSqlPpp/Utility.lhs
src/Database/HsSqlPpp/Utility.o : src/Database/HsSqlPpp/Parser.hi
src/Database/HsSqlPpp/Utility.o : src/Database/HsSqlPpp/Catalog.hi
src/Database/HsSqlPpp/Utility.o : src/Database/HsSqlPpp/Parsing/Lexer.hi
src/Database/HsSqlPpp/Utility.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/Utility.o : src/Database/HsSqlPpp/Internals/AstInternal.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.o : src-extra/utils/Database/HsSqlPpp/Utils/Here.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.o : src-extra/utils/Database/HsSqlPpp/Utils/Here.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Joins.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Joins.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Joins.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Joins.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Dml.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Dml.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Dml.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Dml.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Misc.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Misc.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Misc.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Misc.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.o : src/Database/HsSqlPpp/Ast.hi
src/Database/HsSqlPpp/Pretty.o : src/Database/HsSqlPpp/Pretty.lhs
src/Database/HsSqlPpp/Pretty.o : src/Database/HsSqlPpp/Internals/StringLike.hi
src/Database/HsSqlPpp/Pretty.o : src/Database/HsSqlPpp/SqlDialect.hi
src/Database/HsSqlPpp/Pretty.o : src/Database/HsSqlPpp/Annotation.hi
src/Database/HsSqlPpp/Pretty.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TestUtils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Misc.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Dml.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Joins.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Utils/GroomUtils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src/Database/HsSqlPpp/Utility.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src/Database/HsSqlPpp/Pretty.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src/Database/HsSqlPpp/Parser.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.lhs
src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TestUtils.hi
src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : src/Database/HsSqlPpp/Utility.hi
src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : src/Database/HsSqlPpp/Quote.hi
src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : src/Database/HsSqlPpp/Pretty.hi
src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src-extra/tests/Database/HsSqlPpp/Utils/GroomUtils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src/Database/HsSqlPpp/Utility.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src/Database/HsSqlPpp/Pretty.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src/Database/HsSqlPpp/Types.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src/Database/HsSqlPpp/TypeChecker.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src/Database/HsSqlPpp/Parser.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.o : src/Database/HsSqlPpp/Types.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.o : src/Database/HsSqlPpp/Types.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.o : src/Database/HsSqlPpp/TypeChecker.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o : src/Database/HsSqlPpp/Types.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.o : src-extra/tests/Database/HsSqlPpp/Tests/TpchData.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.o : src/Database/HsSqlPpp/Types.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.o : src/Database/HsSqlPpp/Types.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.o : src/Database/HsSqlPpp/Types.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.o : src/Database/HsSqlPpp/TypeChecker.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TSQL.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TSQL.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TSQL.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TSQL.o : src/Database/HsSqlPpp/Types.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TSQL.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Issues.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Issues.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Issues.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Issues.o : src/Database/HsSqlPpp/TypeChecker.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Issues.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Issues.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TSQL.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Tests.o : src-extra/tests/Database/HsSqlPpp/Tests/Tests.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Tests.o : src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.hi
src-extra/tests/Database/HsSqlPpp/Tests/Tests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.hi
src-extra/tests/Database/HsSqlPpp/Tests/Tests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.hi
src-extra/tests/Tests.o : src-extra/tests/Tests.lhs
src-extra/tests/Tests.o : src-extra/tests/Database/HsSqlPpp/Tests/Tests.hi
# DO NOT DELETE: End of Haskell dependencies
