# DO NOT DELETE: Beginning of Haskell dependencies
src-extra/docutil/Text/DocTool/Parser.o : src-extra/docutil/Text/DocTool/Parser.lhs
src-extra/docutil/Text/DocTool/DocTool.o : src-extra/docutil/Text/DocTool/DocTool.lhs
src-extra/docutil/Text/DocTool/DocTool.o : src-extra/docutil/Text/DocTool/Parser.hi
src/Database/HsSqlPpp/Parsing/ParseErrors.o : src/Database/HsSqlPpp/Parsing/ParseErrors.lhs
src-extra/tests/Database/HsSqlPpp/Utils/GroomUtils.o : src-extra/tests/Database/HsSqlPpp/Utils/GroomUtils.lhs
src-extra/catalogReader/Database/HsSqlPpp/Utils/PgUtils.o : src-extra/catalogReader/Database/HsSqlPpp/Utils/PgUtils.lhs
src-extra/catalogReader/Database/HsSqlPpp/Utils/Here.o : src-extra/catalogReader/Database/HsSqlPpp/Utils/Here.lhs
src/Database/HsSqlPpp/Utils/Utils.o : src/Database/HsSqlPpp/Utils/Utils.lhs
src/Database/HsSqlPpp/SqlDialect.o : src/Database/HsSqlPpp/SqlDialect.lhs
src/Database/HsSqlPpp/Parsing/Lexer.o : src/Database/HsSqlPpp/Parsing/Lexer.lhs
src/Database/HsSqlPpp/Parsing/Lexer.o : src/Database/HsSqlPpp/SqlDialect.hi
src/Database/HsSqlPpp/Parsing/Lexer.o : src/Database/HsSqlPpp/Utils/Utils.hi
src/Database/HsSqlPpp/Parsing/Lexer.o : src/Database/HsSqlPpp/Parsing/ParseErrors.hi
src/Database/HsSqlPpp/Internals/TypesInternal.o : src/Database/HsSqlPpp/Internals/TypesInternal.lhs
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.lhs
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o : src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.lhs
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
src/Database/HsSqlPpp/Catalog.o : src/Database/HsSqlPpp/Catalog.lhs
src/Database/HsSqlPpp/Catalog.o : src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.hi
src/Database/HsSqlPpp/Catalog.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
src-extra/tests/Database/HsSqlPpp/Tests/TpchData.o : src-extra/tests/Database/HsSqlPpp/Tests/TpchData.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TpchData.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/tests/Database/HsSqlPpp/Tests/TpchData.o : src-extra/catalogReader/Database/HsSqlPpp/Utils/Here.hi
src-extra/catalogReader/Database/HsSqlPpp/Utils/CatalogReader.o : src-extra/catalogReader/Database/HsSqlPpp/Utils/CatalogReader.lhs
src-extra/catalogReader/Database/HsSqlPpp/Utils/CatalogReader.o : src-extra/catalogReader/Database/HsSqlPpp/Utils/PgUtils.hi
src-extra/catalogReader/Database/HsSqlPpp/Utils/CatalogReader.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
src-extra/catalogReader/Database/HsSqlPpp/Utils/CatalogReader.o : src-extra/catalogReader/Database/HsSqlPpp/Utils/Here.hi
src-extra/devel-util/MakeDefaultTemplate1Catalog.o : src-extra/devel-util/MakeDefaultTemplate1Catalog.lhs
src-extra/devel-util/MakeDefaultTemplate1Catalog.o : src-extra/catalogReader/Database/HsSqlPpp/Utils/PgUtils.hi
src-extra/devel-util/MakeDefaultTemplate1Catalog.o : src-extra/catalogReader/Database/HsSqlPpp/Utils/CatalogReader.hi
src-extra/devel-util/MakeDefaultTemplate1Catalog.o : src-extra/catalogReader/Database/HsSqlPpp/Utils/Here.hi
src/Database/HsSqlPpp/Types.o : src/Database/HsSqlPpp/Types.lhs
src/Database/HsSqlPpp/Types.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/Internals/TypeChecking/OldTediousTypeUtils.o : src/Database/HsSqlPpp/Internals/TypeChecking/OldTediousTypeUtils.lhs
src/Database/HsSqlPpp/Internals/TypeChecking/OldTediousTypeUtils.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.o : src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.lhs
src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.o : src/Database/HsSqlPpp/Internals/TypeChecking/OldTediousTypeUtils.hi
src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o : src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.lhs
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o : src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.hi
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/Internals/TypeChecking/Environment.o : src/Database/HsSqlPpp/Internals/TypeChecking/Environment.lhs
src/Database/HsSqlPpp/Internals/TypeChecking/Environment.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
src/Database/HsSqlPpp/Internals/TypeChecking/Environment.o : src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.hi
src/Database/HsSqlPpp/Internals/TypeChecking/Environment.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/Internals/AstInternal.o : src/Database/HsSqlPpp/Internals/AstInternal.hs
src/Database/HsSqlPpp/Internals/AstInternal.o : src/Database/HsSqlPpp/Utils/Utils.hi
src/Database/HsSqlPpp/Internals/AstInternal.o : src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.hi
src/Database/HsSqlPpp/Internals/AstInternal.o : src/Database/HsSqlPpp/Internals/TypeChecking/Environment.hi
src/Database/HsSqlPpp/Internals/AstInternal.o : src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.hi
src/Database/HsSqlPpp/Internals/AstInternal.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/TypeChecker.o : src/Database/HsSqlPpp/TypeChecker.lhs
src/Database/HsSqlPpp/TypeChecker.o : src/Database/HsSqlPpp/Internals/AstInternal.hi
src/Database/HsSqlPpp/Annotation.o : src/Database/HsSqlPpp/Annotation.lhs
src/Database/HsSqlPpp/Annotation.o : src/Database/HsSqlPpp/Internals/AstInternal.hi
src-extra/tests/Database/HsSqlPpp/Tests/TestUtils.o : src-extra/tests/Database/HsSqlPpp/Tests/TestUtils.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TestUtils.o : src/Database/HsSqlPpp/Annotation.hi
src/Database/HsSqlPpp/Ast.o : src/Database/HsSqlPpp/Ast.lhs
src/Database/HsSqlPpp/Ast.o : src/Database/HsSqlPpp/Internals/AstInternal.hi
src/Database/HsSqlPpp/Parsing/ParserInternal.o : src/Database/HsSqlPpp/Parsing/ParserInternal.lhs
src/Database/HsSqlPpp/Parsing/ParserInternal.o : src/Database/HsSqlPpp/SqlDialect.hi
src/Database/HsSqlPpp/Parsing/ParserInternal.o : src/Database/HsSqlPpp/Utils/Utils.hi
src/Database/HsSqlPpp/Parsing/ParserInternal.o : src/Database/HsSqlPpp/Annotation.hi
src/Database/HsSqlPpp/Parsing/ParserInternal.o : src/Database/HsSqlPpp/Ast.hi
src/Database/HsSqlPpp/Parsing/ParserInternal.o : src/Database/HsSqlPpp/Parsing/ParseErrors.hi
src/Database/HsSqlPpp/Parsing/ParserInternal.o : src/Database/HsSqlPpp/Parsing/Lexer.hi
src/Database/HsSqlPpp/Parser.o : src/Database/HsSqlPpp/Parser.lhs
src/Database/HsSqlPpp/Parser.o : src/Database/HsSqlPpp/Parsing/ParserInternal.hi
src/Database/HsSqlPpp/Utility.o : src/Database/HsSqlPpp/Utility.lhs
src/Database/HsSqlPpp/Utility.o : src/Database/HsSqlPpp/Parser.hi
src/Database/HsSqlPpp/Utility.o : src/Database/HsSqlPpp/Catalog.hi
src/Database/HsSqlPpp/Utility.o : src/Database/HsSqlPpp/Parsing/Lexer.hi
src/Database/HsSqlPpp/Utility.o : src/Database/HsSqlPpp/Internals/TypesInternal.hi
src/Database/HsSqlPpp/Utility.o : src/Database/HsSqlPpp/Internals/AstInternal.hi
src-extra/examples/Lex.o : src-extra/examples/Lex.lhs
src-extra/examples/Lex.o : src/Database/HsSqlPpp/SqlDialect.hi
src-extra/examples/Lex.o : src/Database/HsSqlPpp/Utility.hi
src-extra/examples/Parse.o : src-extra/examples/Parse.lhs
src-extra/examples/Parse.o : src/Database/HsSqlPpp/Parser.hi
src-extra/examples/Parse2.o : src-extra/examples/Parse2.lhs
src-extra/examples/Parse2.o : src-extra/tests/Database/HsSqlPpp/Utils/GroomUtils.hi
src-extra/examples/Parse2.o : src/Database/HsSqlPpp/Parser.hi
src-extra/examples/Parse3.o : src-extra/examples/Parse3.lhs
src-extra/examples/Parse3.o : src-extra/tests/Database/HsSqlPpp/Utils/GroomUtils.hi
src-extra/examples/Parse3.o : src/Database/HsSqlPpp/Parser.hi
src/Database/HsSqlPpp/Pretty.o : src/Database/HsSqlPpp/Pretty.lhs
src/Database/HsSqlPpp/Pretty.o : src/Database/HsSqlPpp/SqlDialect.hi
src/Database/HsSqlPpp/Pretty.o : src/Database/HsSqlPpp/Utils/Utils.hi
src/Database/HsSqlPpp/Pretty.o : src/Database/HsSqlPpp/Annotation.hi
src/Database/HsSqlPpp/Pretty.o : src/Database/HsSqlPpp/Ast.hi
src-extra/examples/PPPTest.o : src-extra/examples/PPPTest.lhs
src-extra/examples/PPPTest.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/examples/PPPTest.o : src/Database/HsSqlPpp/Utility.hi
src-extra/examples/PPPTest.o : src/Database/HsSqlPpp/Pretty.hi
src-extra/examples/PPPTest.o : src/Database/HsSqlPpp/Parser.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src-extra/tests/Database/HsSqlPpp/Utils/GroomUtils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src/Database/HsSqlPpp/Utility.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src/Database/HsSqlPpp/Pretty.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src/Database/HsSqlPpp/Types.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src/Database/HsSqlPpp/TypeChecker.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o : src/Database/HsSqlPpp/Parser.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.o : src/Database/HsSqlPpp/Types.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.o : src/Database/HsSqlPpp/Types.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.o : src/Database/HsSqlPpp/TypeChecker.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o : src/Database/HsSqlPpp/Types.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.o : src-extra/tests/Database/HsSqlPpp/Tests/TpchData.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.o : src/Database/HsSqlPpp/Types.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.o : src/Database/HsSqlPpp/Types.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.o : src/Database/HsSqlPpp/Types.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.lhs
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.hi
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.hi
src/Database/HsSqlPpp/Quote.o : src/Database/HsSqlPpp/Quote.lhs
src/Database/HsSqlPpp/Quote.o : src/Database/HsSqlPpp/Ast.hi
src/Database/HsSqlPpp/Quote.o : src/Database/HsSqlPpp/Ast.hi
src/Database/HsSqlPpp/Quote.o : src/Database/HsSqlPpp/Annotation.hi
src/Database/HsSqlPpp/Quote.o : src/Database/HsSqlPpp/Parsing/ParserInternal.hi
src-extra/examples/MakeSelect.o : src-extra/examples/MakeSelect.lhs
src-extra/examples/MakeSelect.o : src/Database/HsSqlPpp/Pretty.hi
src-extra/examples/MakeSelect.o : src/Database/HsSqlPpp/Ast.hi
src-extra/examples/MakeSelect.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/examples/TypeCheck3.o : src-extra/examples/TypeCheck3.lhs
src-extra/examples/TypeCheck3.o : src-extra/tests/Database/HsSqlPpp/Tests/TpchData.hi
src-extra/examples/TypeCheck3.o : src-extra/tests/Database/HsSqlPpp/Utils/GroomUtils.hi
src-extra/examples/TypeCheck3.o : src/Database/HsSqlPpp/Ast.hi
src-extra/examples/TypeCheck3.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/examples/TypeCheck3.o : src/Database/HsSqlPpp/TypeChecker.hi
src-extra/examples/TypeCheck3.o : src/Database/HsSqlPpp/Parser.hi
src-extra/examples/TypeCheck2.o : src-extra/examples/TypeCheck2.lhs
src-extra/examples/TypeCheck2.o : src/Database/HsSqlPpp/Utility.hi
src-extra/examples/TypeCheck2.o : src/Database/HsSqlPpp/Ast.hi
src-extra/examples/TypeCheck2.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/examples/TypeCheck2.o : src/Database/HsSqlPpp/Types.hi
src-extra/examples/TypeCheck2.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/examples/TypeCheck2.o : src/Database/HsSqlPpp/TypeChecker.hi
src-extra/examples/TypeCheck2.o : src/Database/HsSqlPpp/Parser.hi
src-extra/examples/TypeCheck.o : src-extra/examples/TypeCheck.lhs
src-extra/examples/TypeCheck.o : src/Database/HsSqlPpp/Ast.hi
src-extra/examples/TypeCheck.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/examples/TypeCheck.o : src/Database/HsSqlPpp/Types.hi
src-extra/examples/TypeCheck.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/examples/TypeCheck.o : src/Database/HsSqlPpp/TypeChecker.hi
src-extra/examples/TypeCheck.o : src/Database/HsSqlPpp/Parser.hi
src-extra/examples/TypeCheckDB.o : src-extra/examples/TypeCheckDB.lhs
src-extra/examples/TypeCheckDB.o : src-extra/catalogReader/Database/HsSqlPpp/Utils/CatalogReader.hi
src-extra/examples/TypeCheckDB.o : src/Database/HsSqlPpp/Ast.hi
src-extra/examples/TypeCheckDB.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/examples/TypeCheckDB.o : src/Database/HsSqlPpp/Types.hi
src-extra/examples/TypeCheckDB.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/examples/TypeCheckDB.o : src/Database/HsSqlPpp/TypeChecker.hi
src-extra/examples/TypeCheckDB.o : src/Database/HsSqlPpp/Parser.hi
src-extra/examples/TypeCheckMystery.o : src-extra/examples/TypeCheckMystery.lhs
src-extra/examples/TypeCheckMystery.o : src/Database/HsSqlPpp/Utility.hi
src-extra/examples/TypeCheckMystery.o : src/Database/HsSqlPpp/Ast.hi
src-extra/examples/TypeCheckMystery.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/examples/TypeCheckMystery.o : src/Database/HsSqlPpp/Types.hi
src-extra/examples/TypeCheckMystery.o : src/Database/HsSqlPpp/Catalog.hi
src-extra/examples/TypeCheckMystery.o : src/Database/HsSqlPpp/TypeChecker.hi
src-extra/examples/TypeCheckMystery.o : src/Database/HsSqlPpp/Parser.hi
src-extra/examples/FixSqlServerTpchSyntax.o : src-extra/examples/FixSqlServerTpchSyntax.lhs
src-extra/examples/FixSqlServerTpchSyntax.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/examples/FixSqlServerTpchSyntax.o : src/Database/HsSqlPpp/Quote.hi
src-extra/examples/FixSqlServerTpchSyntax.o : src/Database/HsSqlPpp/Pretty.hi
src-extra/examples/FixSqlServerTpchSyntax.o : src/Database/HsSqlPpp/Ast.hi
src-extra/examples/FixSqlServerTpchSyntax.o : src/Database/HsSqlPpp/Parser.hi
src-extra/examples/QQ.o : src-extra/examples/QQ.lhs
src-extra/examples/QQ.o : src/Database/HsSqlPpp/Pretty.hi
src-extra/examples/QQ.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/examples/QQ.o : src/Database/HsSqlPpp/Quote.hi
src-extra/examples/QQ.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.lhs
src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TestUtils.hi
src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : src/Database/HsSqlPpp/Utility.hi
src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : src/Database/HsSqlPpp/Quote.hi
src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : src/Database/HsSqlPpp/Pretty.hi
src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.o : src-extra/catalogReader/Database/HsSqlPpp/Utils/Here.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.o : src-extra/catalogReader/Database/HsSqlPpp/Utils/Here.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Joins.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Joins.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Joins.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Joins.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Dml.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Dml.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Dml.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Dml.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Misc.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Misc.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Misc.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Misc.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/TestUtils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Misc.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Dml.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Joins.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src-extra/tests/Database/HsSqlPpp/Utils/GroomUtils.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src/Database/HsSqlPpp/Utility.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src/Database/HsSqlPpp/Pretty.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src/Database/HsSqlPpp/Parser.hi
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o : src/Database/HsSqlPpp/Ast.hi
src-extra/tests/Database/HsSqlPpp/Tests/Tests.o : src-extra/tests/Database/HsSqlPpp/Tests/Tests.lhs
src-extra/tests/Database/HsSqlPpp/Tests/Tests.o : src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.hi
src-extra/tests/Database/HsSqlPpp/Tests/Tests.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.hi
src-extra/tests/Database/HsSqlPpp/Tests/Tests.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.hi
src-extra/tests/Tests.o : src-extra/tests/Tests.lhs
src-extra/tests/Tests.o : src-extra/tests/Database/HsSqlPpp/Tests/Tests.hi
src-extra/docutil/TestFileProcessor.o : src-extra/docutil/TestFileProcessor.lhs
src-extra/docutil/TestFileProcessor.o : src-extra/tests/Database/HsSqlPpp/Utils/GroomUtils.hi
src-extra/docutil/TestFileProcessor.o : src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.hi
src-extra/docutil/TestFileProcessor.o : src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.hi
src-extra/docutil/TestFileProcessor.o : src-extra/catalogReader/Database/HsSqlPpp/Utils/Here.hi
src-extra/docutil/TestFileProcessor.o : src/Database/HsSqlPpp/Utils/Utils.hi
src-extra/docutil/MakeWebsite.o : src-extra/docutil/MakeWebsite.lhs
src-extra/docutil/MakeWebsite.o : src-extra/docutil/TestFileProcessor.hi
src-extra/docutil/MakeWebsite.o : src-extra/docutil/Text/DocTool/DocTool.hi
src-extra/docutil/DevelTool.o : src-extra/docutil/DevelTool.lhs
src-extra/docutil/DevelTool.o : src-extra/docutil/MakeWebsite.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/ExtensionsUtils.o : src-extra/extensions/Database/HsSqlPpp/Extensions/ExtensionsUtils.lhs
src-extra/extensions/Database/HsSqlPpp/Extensions/ExtensionsUtils.o : src/Database/HsSqlPpp/Ast.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/AstUtils.o : src-extra/extensions/Database/HsSqlPpp/Extensions/AstUtils.lhs
src-extra/extensions/Database/HsSqlPpp/Extensions/AstUtils.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/AstUtils.o : src/Database/HsSqlPpp/Ast.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/TransitionConstraints.o : src-extra/extensions/Database/HsSqlPpp/Extensions/TransitionConstraints.lhs
src-extra/extensions/Database/HsSqlPpp/Extensions/TransitionConstraints.o : src-extra/extensions/Database/HsSqlPpp/Extensions/AstUtils.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/TransitionConstraints.o : src/Database/HsSqlPpp/Quote.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/TransitionConstraints.o : src-extra/extensions/Database/HsSqlPpp/Extensions/ExtensionsUtils.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/TransitionConstraints.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/TransitionConstraints.o : src/Database/HsSqlPpp/Ast.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/Modules.o : src-extra/extensions/Database/HsSqlPpp/Extensions/Modules.lhs
src-extra/extensions/Database/HsSqlPpp/Extensions/Modules.o : src-extra/extensions/Database/HsSqlPpp/Extensions/AstUtils.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/Modules.o : src-extra/extensions/Database/HsSqlPpp/Extensions/ExtensionsUtils.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/Modules.o : src/Database/HsSqlPpp/Quote.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/Modules.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/Modules.o : src/Database/HsSqlPpp/Ast.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateAssertion.o : src-extra/extensions/Database/HsSqlPpp/Extensions/CreateAssertion.lhs
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateAssertion.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateAssertion.o : src-extra/extensions/Database/HsSqlPpp/Extensions/AstUtils.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateAssertion.o : src/Database/HsSqlPpp/Quote.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateAssertion.o : src/Database/HsSqlPpp/Utils/Utils.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateAssertion.o : src/Database/HsSqlPpp/Parser.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateAssertion.o : src/Database/HsSqlPpp/Ast.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateVar.o : src-extra/extensions/Database/HsSqlPpp/Extensions/CreateVar.lhs
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateVar.o : src-extra/extensions/Database/HsSqlPpp/Extensions/AstUtils.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateVar.o : src-extra/extensions/Database/HsSqlPpp/Extensions/CreateAssertion.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateVar.o : src/Database/HsSqlPpp/Pretty.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateVar.o : src/Database/HsSqlPpp/Quote.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateVar.o : src-extra/extensions/Database/HsSqlPpp/Extensions/ExtensionsUtils.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateVar.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateVar.o : src/Database/HsSqlPpp/Ast.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CardinalityRestrict.o : src-extra/extensions/Database/HsSqlPpp/Extensions/CardinalityRestrict.lhs
src-extra/extensions/Database/HsSqlPpp/Extensions/CardinalityRestrict.o : src-extra/extensions/Database/HsSqlPpp/Extensions/AstUtils.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CardinalityRestrict.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CardinalityRestrict.o : src-extra/extensions/Database/HsSqlPpp/Extensions/CreateAssertion.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CardinalityRestrict.o : src/Database/HsSqlPpp/Pretty.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CardinalityRestrict.o : src/Database/HsSqlPpp/Quote.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CardinalityRestrict.o : src-extra/extensions/Database/HsSqlPpp/Extensions/ExtensionsUtils.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/CardinalityRestrict.o : src/Database/HsSqlPpp/Ast.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/SimplifiedCatalog.o : src-extra/extensions/Database/HsSqlPpp/Extensions/SimplifiedCatalog.lhs
src-extra/extensions/Database/HsSqlPpp/Extensions/SimplifiedCatalog.o : src-extra/extensions/Database/HsSqlPpp/Extensions/AstUtils.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/SimplifiedCatalog.o : src/Database/HsSqlPpp/Quote.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/SimplifiedCatalog.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/SimplifiedCatalog.o : src/Database/HsSqlPpp/Ast.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/DenormSyntax.o : src-extra/extensions/Database/HsSqlPpp/Extensions/DenormSyntax.lhs
src-extra/extensions/Database/HsSqlPpp/Extensions/DenormSyntax.o : src-extra/extensions/Database/HsSqlPpp/Extensions/AstUtils.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/DenormSyntax.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/DenormSyntax.o : src-extra/catalogReader/Database/HsSqlPpp/Utils/Here.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/DenormSyntax.o : src/Database/HsSqlPpp/Parsing/Lexer.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/DenormSyntax.o : src/Database/HsSqlPpp/Parsing/ParserInternal.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/DenormSyntax.o : src/Database/HsSqlPpp/Utility.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/DenormSyntax.o : src/Database/HsSqlPpp/Ast.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/Denormalized6nf.o : src-extra/extensions/Database/HsSqlPpp/Extensions/Denormalized6nf.lhs
src-extra/extensions/Database/HsSqlPpp/Extensions/Denormalized6nf.o : src-extra/extensions/Database/HsSqlPpp/Extensions/AstUtils.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/Denormalized6nf.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/Denormalized6nf.o : src/Database/HsSqlPpp/Quote.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/Denormalized6nf.o : src/Database/HsSqlPpp/Ast.hi
src-extra/extensions/Database/HsSqlPpp/Extensions/Denormalized6nf.o : src-extra/extensions/Database/HsSqlPpp/Extensions/DenormSyntax.hi
src-extra/chaos/extensions/ChaosExtensions.o : src-extra/chaos/extensions/ChaosExtensions.lhs
src-extra/chaos/extensions/ChaosExtensions.o : src-extra/extensions/Database/HsSqlPpp/Extensions/AstUtils.hi
src-extra/chaos/extensions/ChaosExtensions.o : src-extra/extensions/Database/HsSqlPpp/Extensions/Denormalized6nf.hi
src-extra/chaos/extensions/ChaosExtensions.o : src-extra/extensions/Database/HsSqlPpp/Extensions/SimplifiedCatalog.hi
src-extra/chaos/extensions/ChaosExtensions.o : src-extra/extensions/Database/HsSqlPpp/Extensions/CardinalityRestrict.hi
src-extra/chaos/extensions/ChaosExtensions.o : src-extra/extensions/Database/HsSqlPpp/Extensions/CreateVar.hi
src-extra/chaos/extensions/ChaosExtensions.o : src-extra/extensions/Database/HsSqlPpp/Extensions/CreateAssertion.hi
src-extra/chaos/extensions/ChaosExtensions.o : src-extra/extensions/Database/HsSqlPpp/Extensions/Modules.hi
src-extra/chaos/extensions/ChaosExtensions.o : src-extra/extensions/Database/HsSqlPpp/Extensions/TransitionConstraints.hi
src-extra/chaos/extensions/ChaosExtensions.o : src/Database/HsSqlPpp/Quote.hi
src-extra/chaos/extensions/ChaosExtensions.o : src-extra/extensions/Database/HsSqlPpp/Extensions/ExtensionsUtils.hi
src-extra/chaos/extensions/ChaosExtensions.o : src/Database/HsSqlPpp/Annotation.hi
src-extra/chaos/extensions/ChaosExtensions.o : src/Database/HsSqlPpp/Pretty.hi
src-extra/chaos/extensions/ChaosExtensions.o : src/Database/HsSqlPpp/Ast.hi
src-extra/h7c/h7c.o : src-extra/h7c/h7c.lhs
src-extra/h7c/h7c.o : src-extra/chaos/extensions/ChaosExtensions.hi
src-extra/h7c/h7c.o : src/Database/HsSqlPpp/Pretty.hi
src-extra/h7c/h7c.o : src/Database/HsSqlPpp/Ast.hi
src-extra/h7c/h7c.o : src/Database/HsSqlPpp/Parser.hi
# DO NOT DELETE: End of Haskell dependencies
