hssqlppp/tests/Tests : hssqlppp/tests/Tests.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Tests.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o \
hssqlppp/src/Database/HsSqlPpp/Ast.o \
hssqlppp/src/Database/HsSqlPpp/Parser.o \
hssqlppp/src/Database/HsSqlPpp/Pretty.o \
hssqlppp/src/Database/HsSqlPpp/Utility.o \
hssqlppp/tests/Database/HsSqlPpp/Utils/GroomUtils.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Joins.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Dml.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Misc.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.o \
hssqlppp/src/Database/HsSqlPpp/Internals/AstInternal.o \
hssqlppp/src/Database/HsSqlPpp/Internals/TypesInternal.o \
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/Environment.o \
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
hssqlppp/src/Database/HsSqlPpp/Utils/Utils.o \
hssqlppp/src/Database/HsSqlPpp/SqlDialect.o \
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.o \
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/SqlTypeConversion.o \
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/OldTediousTypeUtils.o \
hssqlppp/src/Database/HsSqlPpp/Parsing/ParserInternal.o \
hssqlppp/src/Database/HsSqlPpp/Parsing/Lexer.o \
hssqlppp/src/Database/HsSqlPpp/Parsing/ParseErrors.o \
hssqlppp/src/Database/HsSqlPpp/Annotation.o \
hssqlppp/src/Database/HsSqlPpp/Catalog.o \
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTSQLCatalog.o \
hssqlppp/tests/Database/HsSqlPpp/Utils/Here.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TSQL.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Issues.o \
hssqlppp/src/Database/HsSqlPpp/TypeChecker.o \
hssqlppp/src/Database/HsSqlPpp/Types.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TpchData.o \
hssqlppp-th/src/Database/HsSqlPpp/Quote.o
	$(HC) $(HC_OPTS) -o hssqlppp/tests/Tests hssqlppp/tests/Tests.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Tests.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o \
hssqlppp/src/Database/HsSqlPpp/Ast.o \
hssqlppp/src/Database/HsSqlPpp/Parser.o \
hssqlppp/src/Database/HsSqlPpp/Pretty.o \
hssqlppp/src/Database/HsSqlPpp/Utility.o \
hssqlppp/tests/Database/HsSqlPpp/Utils/GroomUtils.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Utils.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/ScalarExprs.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/MiscQueryExprs.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/CombineQueryExprs.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/SelectLists.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/TableRefs.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Joins.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Dml.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Misc.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/Parsing/SqlServer.o \
hssqlppp/src/Database/HsSqlPpp/Internals/AstInternal.o \
hssqlppp/src/Database/HsSqlPpp/Internals/TypesInternal.o \
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/Environment.o \
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
hssqlppp/src/Database/HsSqlPpp/Utils/Utils.o \
hssqlppp/src/Database/HsSqlPpp/SqlDialect.o \
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/OldTypeConversion.o \
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/SqlTypeConversion.o \
hssqlppp/src/Database/HsSqlPpp/Internals/TypeChecking/OldTediousTypeUtils.o \
hssqlppp/src/Database/HsSqlPpp/Parsing/ParserInternal.o \
hssqlppp/src/Database/HsSqlPpp/Parsing/Lexer.o \
hssqlppp/src/Database/HsSqlPpp/Parsing/ParseErrors.o \
hssqlppp/src/Database/HsSqlPpp/Annotation.o \
hssqlppp/src/Database/HsSqlPpp/Catalog.o \
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTSQLCatalog.o \
hssqlppp/tests/Database/HsSqlPpp/Utils/Here.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/ScalarExprs.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleQueryExprs.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Rewrites.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Tpch.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TrefIdentifiers.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/ImplicitCasts.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/TSQL.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TypeChecking/Issues.o \
hssqlppp/src/Database/HsSqlPpp/TypeChecker.o \
hssqlppp/src/Database/HsSqlPpp/Types.o \
hssqlppp/tests/Database/HsSqlPpp/Tests/TpchData.o \
hssqlppp-th/src/Database/HsSqlPpp/Quote.o
src-extra/devel-util/MakeDefaultTemplate1Catalog : src-extra/devel-util/MakeDefaultTemplate1Catalog.o \
hssqlppp/tests/Database/HsSqlPpp/Utils/Here.o \
hssqlppp-pg/src/Database/HsSqlPpp/Utils/CatalogReader.o \
hssqlppp-pg/src/Database/HsSqlPpp/Utils/PgUtils.o \
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
hssqlppp-pg/src/Database/HsSqlPpp/Utils/Here2.o \
hssqlppp/src/Database/HsSqlPpp/Catalog.o \
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTSQLCatalog.o \
hssqlppp/src/Database/HsSqlPpp/Internals/TypesInternal.o
	$(HC) $(HC_OPTS) -o src-extra/devel-util/MakeDefaultTemplate1Catalog src-extra/devel-util/MakeDefaultTemplate1Catalog.o \
hssqlppp/tests/Database/HsSqlPpp/Utils/Here.o \
hssqlppp-pg/src/Database/HsSqlPpp/Utils/CatalogReader.o \
hssqlppp-pg/src/Database/HsSqlPpp/Utils/PgUtils.o \
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
hssqlppp-pg/src/Database/HsSqlPpp/Utils/Here2.o \
hssqlppp/src/Database/HsSqlPpp/Catalog.o \
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
hssqlppp/src/Database/HsSqlPpp/Internals/Catalog/DefaultTSQLCatalog.o \
hssqlppp/src/Database/HsSqlPpp/Internals/TypesInternal.o