src-extra/tests/Tests : src-extra/tests/Tests.o \
src-extra/tests/Database/HsSqlPpp/Tests/Tests.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/FixTree/FixUpIdentifiersTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/FixTree/ExplicitCasts.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/ParameterizedStatementTests.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/Pretty.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Expressions.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Selects.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Dml.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Misc.o \
src-extra/tests/Database/HsSqlPpp/Tests/TestUtils.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
src-extra/util/Database/HsSqlPpp/Utils/Here.o \
src/Database/HsSqlPpp/TypeChecker.o \
src/Database/HsSqlPpp/Types.o \
src/Database/HsSqlPpp/Internals/TypeChecking/Utils.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TableRefTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TpchTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeInferenceTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Literals.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleExpressions.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SpecialFunctions.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/RowCtors.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/MiscExpressions.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleSelects.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CombineSelects.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SelectFrom.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Qualification.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/MiscSelects.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Insert.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Update.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Delete.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Creates.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Plpgsql.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CatalogChaining.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Into.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Drops.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Triggers.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Misc.o \
src-extra/tests/Database/HsSqlPpp/Tests/TpchData.o \
src/Database/HsSqlPpp/Quote.o
	$(HC) $(HC_OPTS) -o src-extra/tests/Tests src-extra/tests/Tests.o \
src-extra/tests/Database/HsSqlPpp/Tests/Tests.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/FixTree/FixUpIdentifiersTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/FixTree/ExplicitCasts.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/QuasiQuoteTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/ParameterizedStatementTests.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/Pretty.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Expressions.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Selects.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Dml.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Misc.o \
src-extra/tests/Database/HsSqlPpp/Tests/TestUtils.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
src-extra/util/Database/HsSqlPpp/Utils/Here.o \
src/Database/HsSqlPpp/TypeChecker.o \
src/Database/HsSqlPpp/Types.o \
src/Database/HsSqlPpp/Internals/TypeChecking/Utils.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TableRefTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TpchTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeInferenceTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Literals.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleExpressions.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SpecialFunctions.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/RowCtors.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/MiscExpressions.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleSelects.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CombineSelects.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SelectFrom.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Qualification.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/MiscSelects.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Insert.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Update.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Delete.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Creates.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Plpgsql.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CatalogChaining.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Into.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Drops.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Triggers.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Misc.o \
src-extra/tests/Database/HsSqlPpp/Tests/TpchData.o \
src/Database/HsSqlPpp/Quote.o
src-extra/devel-util/MakeAntiNodesRunner : src-extra/devel-util/MakeAntiNodesRunner.o \
src-extra/devel-util/MakeAntiNodes.o
	$(HC) $(HC_OPTS) -o src-extra/devel-util/MakeAntiNodesRunner src-extra/devel-util/MakeAntiNodesRunner.o \
src-extra/devel-util/MakeAntiNodes.o
src-extra/devel-util/MakeDefaultTemplate1Catalog : src-extra/devel-util/MakeDefaultTemplate1Catalog.o \
src-extra/util/Database/HsSqlPpp/Utils/Here.o \
src-extra/util/Database/HsSqlPpp/Utils/CatalogReader.o \
src-extra/util/Database/HsSqlPpp/Utils/PgUtils.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Types.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Utils/Utils.o
	$(HC) $(HC_OPTS) -o src-extra/devel-util/MakeDefaultTemplate1Catalog src-extra/devel-util/MakeDefaultTemplate1Catalog.o \
src-extra/util/Database/HsSqlPpp/Utils/Here.o \
src-extra/util/Database/HsSqlPpp/Utils/CatalogReader.o \
src-extra/util/Database/HsSqlPpp/Utils/PgUtils.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Types.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Utils/Utils.o
src-extra/examples/FixSqlServerTpchSyntax : src-extra/examples/FixSqlServerTpchSyntax.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Pretty.o \
src/Database/HsSqlPpp/Quote.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o
	$(HC) $(HC_OPTS) -o src-extra/examples/FixSqlServerTpchSyntax src-extra/examples/FixSqlServerTpchSyntax.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Pretty.o \
src/Database/HsSqlPpp/Quote.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o
src-extra/examples/MakeSelect : src-extra/examples/MakeSelect.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Pretty.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o
	$(HC) $(HC_OPTS) -o src-extra/examples/MakeSelect src-extra/examples/MakeSelect.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Pretty.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o
src-extra/examples/Parse : src-extra/examples/Parse.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o
	$(HC) $(HC_OPTS) -o src-extra/examples/Parse src-extra/examples/Parse.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o
src-extra/examples/Parse2 : src-extra/examples/Parse2.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o
	$(HC) $(HC_OPTS) -o src-extra/examples/Parse2 src-extra/examples/Parse2.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o
src-extra/examples/QQ : src-extra/examples/QQ.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Quote.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Pretty.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o
	$(HC) $(HC_OPTS) -o src-extra/examples/QQ src-extra/examples/QQ.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Quote.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Pretty.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o
src-extra/examples/ShowCatalog : src-extra/examples/ShowCatalog.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/TypeChecker.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
src/Database/HsSqlPpp/Internals/TypeChecking/Utils.o
	$(HC) $(HC_OPTS) -o src-extra/examples/ShowCatalog src-extra/examples/ShowCatalog.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/TypeChecker.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
src/Database/HsSqlPpp/Internals/TypeChecking/Utils.o
src-extra/examples/TypeCheck : src-extra/examples/TypeCheck.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/TypeChecker.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Types.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
src/Database/HsSqlPpp/Internals/TypeChecking/Utils.o
	$(HC) $(HC_OPTS) -o src-extra/examples/TypeCheck src-extra/examples/TypeCheck.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/TypeChecker.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Types.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
src/Database/HsSqlPpp/Internals/TypeChecking/Utils.o
src-extra/examples/TypeCheckDB : src-extra/examples/TypeCheckDB.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/TypeChecker.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Types.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Ast.o \
src-extra/util/Database/HsSqlPpp/Utils/CatalogReader.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
src/Database/HsSqlPpp/Internals/TypeChecking/Utils.o \
src-extra/util/Database/HsSqlPpp/Utils/Here.o \
src-extra/util/Database/HsSqlPpp/Utils/PgUtils.o
	$(HC) $(HC_OPTS) -o src-extra/examples/TypeCheckDB src-extra/examples/TypeCheckDB.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/TypeChecker.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Types.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Ast.o \
src-extra/util/Database/HsSqlPpp/Utils/CatalogReader.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
src/Database/HsSqlPpp/Internals/TypeChecking/Utils.o \
src-extra/util/Database/HsSqlPpp/Utils/Here.o \
src-extra/util/Database/HsSqlPpp/Utils/PgUtils.o
src-extra/tosort/util/DevelTool : src-extra/tosort/util/DevelTool.o \
src-extra/tosort/util/MakeWebsite.o \
src-extra/tosort/util/Text/DocTool/DocTool.o \
src-extra/tosort/util/TestFileProcessor.o \
src-extra/tosort/util/Text/DocTool/Parser.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src-extra/util/Database/HsSqlPpp/Utils/Here.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/Pretty.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Expressions.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Selects.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Dml.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Misc.o \
src-extra/tests/Database/HsSqlPpp/Tests/TestUtils.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TableRefTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TpchTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeInferenceTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Literals.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleExpressions.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SpecialFunctions.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/RowCtors.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/MiscExpressions.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleSelects.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CombineSelects.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SelectFrom.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Qualification.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/MiscSelects.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Insert.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Update.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Delete.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Creates.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Plpgsql.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CatalogChaining.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Into.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Drops.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Triggers.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Misc.o \
src/Database/HsSqlPpp/TypeChecker.o \
src/Database/HsSqlPpp/Types.o \
src/Database/HsSqlPpp/Internals/TypeChecking/Utils.o \
src-extra/tests/Database/HsSqlPpp/Tests/TpchData.o \
src/Database/HsSqlPpp/Quote.o
	$(HC) $(HC_OPTS) -o src-extra/tosort/util/DevelTool src-extra/tosort/util/DevelTool.o \
src-extra/tosort/util/MakeWebsite.o \
src-extra/tosort/util/Text/DocTool/DocTool.o \
src-extra/tosort/util/TestFileProcessor.o \
src-extra/tosort/util/Text/DocTool/Parser.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src-extra/util/Database/HsSqlPpp/Utils/Here.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/ParserTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeCheckTests.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/Pretty.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Utils.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Expressions.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Selects.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Dml.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/CreateTable.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/MiscDdl.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/FunctionsDdl.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Plpgsql.o \
src-extra/tests/Database/HsSqlPpp/Tests/Parsing/Misc.o \
src-extra/tests/Database/HsSqlPpp/Tests/TestUtils.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Utils.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TableRefTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TpchTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/TypeInferenceTests.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Literals.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleExpressions.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SpecialFunctions.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/RowCtors.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CaseExpressions.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/MiscExpressions.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SimpleSelects.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CombineSelects.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/SelectFrom.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Joins.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Qualification.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/MiscSelects.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Insert.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Update.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Delete.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Creates.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Plpgsql.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/CatalogChaining.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Into.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Drops.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Triggers.o \
src-extra/tests/Database/HsSqlPpp/Tests/TypeChecking/Misc.o \
src/Database/HsSqlPpp/TypeChecker.o \
src/Database/HsSqlPpp/Types.o \
src/Database/HsSqlPpp/Internals/TypeChecking/Utils.o \
src-extra/tests/Database/HsSqlPpp/Tests/TpchData.o \
src/Database/HsSqlPpp/Quote.o
src-extra/h7c/h7c : src-extra/h7c/h7c.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Pretty.o \
src-extra/chaos/extensions/ChaosExtensions.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/ExtensionsUtils.o \
src/Database/HsSqlPpp/Quote.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/TransitionConstraints.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/Modules.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateAssertion.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateVar.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/CardinalityRestrict.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/SimplifiedCatalog.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/Denormalized6nf.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/AstUtils.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/DenormSyntax.o \
src-extra/util/Database/HsSqlPpp/Utils/Here.o
	$(HC) $(HC_OPTS) -o src-extra/h7c/h7c src-extra/h7c/h7c.o \
src/Database/HsSqlPpp/Parser.o \
src/Database/HsSqlPpp/Ast.o \
src/Database/HsSqlPpp/Pretty.o \
src-extra/chaos/extensions/ChaosExtensions.o \
src/Database/HsSqlPpp/Parsing/ParserInternal.o \
src/Database/HsSqlPpp/Parsing/Lexer.o \
src/Database/HsSqlPpp/Parsing/ParseErrors.o \
src/Database/HsSqlPpp/Internals/AstAnti.o \
src/Database/HsSqlPpp/Annotation.o \
src/Database/HsSqlPpp/Utils/Utils.o \
src/Database/HsSqlPpp/Catalog.o \
src/Database/HsSqlPpp/Internals/AstAnnotation.o \
src/Database/HsSqlPpp/Internals/AstInternal.o \
src/Database/HsSqlPpp/Internals/TypeType.o \
src/Database/HsSqlPpp/Internals/Catalog/CatalogInternal.o \
src/Database/HsSqlPpp/Internals/TypeChecking/TypeConversion.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindings.o \
src/Database/HsSqlPpp/Internals/TypeChecking/ErrorUtils.o \
src/Database/HsSqlPpp/Internals/TypeChecking/IDEnv.o \
src/Database/HsSqlPpp/Internals/TypeChecking/LocalBindingsInternal.o \
src/Database/HsSqlPpp/Internals/AnnotationUtils.o \
src/Database/HsSqlPpp/Internals/Catalog/DefaultTemplate1Catalog.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/ExtensionsUtils.o \
src/Database/HsSqlPpp/Quote.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/TransitionConstraints.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/Modules.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateAssertion.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/CreateVar.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/CardinalityRestrict.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/SimplifiedCatalog.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/Denormalized6nf.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/AstUtils.o \
src-extra/extensions/Database/HsSqlPpp/Extensions/DenormSyntax.o \
src-extra/util/Database/HsSqlPpp/Utils/Here.o