module PGTypes where

import TypeType

defaultTypeNames :: [Type]
defaultTypeNames = [
    ArrayType (Pseudo Cstring),
    ArrayType (Pseudo Record),
    ArrayType (ScalarType "abstime"),
    ArrayType (ScalarType "aclitem"),
    ArrayType (ScalarType "bit"),
    ArrayType (ScalarType "bool"),
    ArrayType (ScalarType "box"),
    ArrayType (ScalarType "bpchar"),
    ArrayType (ScalarType "bytea"),
    ArrayType (ScalarType "char"),
    ArrayType (ScalarType "cid"),
    ArrayType (ScalarType "cidr"),
    ArrayType (ScalarType "circle"),
    ArrayType (ScalarType "date"),
    ArrayType (ScalarType "float4"),
    ArrayType (ScalarType "float8"),
    ArrayType (ScalarType "gtsvector"),
    ArrayType (ScalarType "inet"),
    ArrayType (ScalarType "int2"),
    ArrayType (ScalarType "int2vector"),
    ArrayType (ScalarType "int4"),
    ArrayType (ScalarType "int8"),
    ArrayType (ScalarType "interval"),
    ArrayType (ScalarType "line"),
    ArrayType (ScalarType "lseg"),
    ArrayType (ScalarType "macaddr"),
    ArrayType (ScalarType "money"),
    ArrayType (ScalarType "name"),
    ArrayType (ScalarType "numeric"),
    ArrayType (ScalarType "oid"),
    ArrayType (ScalarType "oidvector"),
    ArrayType (ScalarType "path"),
    ArrayType (ScalarType "point"),
    ArrayType (ScalarType "polygon"),
    ArrayType (ScalarType "refcursor"),
    ArrayType (ScalarType "regclass"),
    ArrayType (ScalarType "regconfig"),
    ArrayType (ScalarType "regdictionary"),
    ArrayType (ScalarType "regoper"),
    ArrayType (ScalarType "regoperator"),
    ArrayType (ScalarType "regproc"),
    ArrayType (ScalarType "regprocedure"),
    ArrayType (ScalarType "regtype"),
    ArrayType (ScalarType "reltime"),
    ArrayType (ScalarType "text"),
    ArrayType (ScalarType "tid"),
    ArrayType (ScalarType "time"),
    ArrayType (ScalarType "timestamp"),
    ArrayType (ScalarType "timestamptz"),
    ArrayType (ScalarType "timetz"),
    ArrayType (ScalarType "tinterval"),
    ArrayType (ScalarType "tsquery"),
    ArrayType (ScalarType "tsvector"),
    ArrayType (ScalarType "txid_snapshot"),
    ArrayType (ScalarType "uuid"),
    ArrayType (ScalarType "varbit"),
    ArrayType (ScalarType "varchar"),
    ArrayType (ScalarType "xid"),
    ArrayType (ScalarType "xml"),
    CompositeType "pg_aggregate",
    CompositeType "pg_am",
    CompositeType "pg_amop",
    CompositeType "pg_amproc",
    CompositeType "pg_attrdef",
    CompositeType "pg_attribute",
    CompositeType "pg_authid",
    CompositeType "pg_auth_members",
    CompositeType "pg_cast",
    CompositeType "pg_class",
    CompositeType "pg_constraint",
    CompositeType "pg_conversion",
    CompositeType "pg_cursors",
    CompositeType "pg_database",
    CompositeType "pg_depend",
    CompositeType "pg_description",
    CompositeType "pg_enum",
    CompositeType "pg_foreign_data_wrapper",
    CompositeType "pg_foreign_server",
    CompositeType "pg_group",
    CompositeType "pg_index",
    CompositeType "pg_indexes",
    CompositeType "pg_inherits",
    CompositeType "pg_language",
    CompositeType "pg_largeobject",
    CompositeType "pg_listener",
    CompositeType "pg_locks",
    CompositeType "pg_namespace",
    CompositeType "pg_opclass",
    CompositeType "pg_operator",
    CompositeType "pg_opfamily",
    CompositeType "pg_pltemplate",
    CompositeType "pg_prepared_statements",
    CompositeType "pg_prepared_xacts",
    CompositeType "pg_proc",
    CompositeType "pg_rewrite",
    CompositeType "pg_roles",
    CompositeType "pg_rules",
    CompositeType "pg_settings",
    CompositeType "pg_shadow",
    CompositeType "pg_shdepend",
    CompositeType "pg_shdescription",
    CompositeType "pg_stat_activity",
    CompositeType "pg_stat_all_indexes",
    CompositeType "pg_stat_all_tables",
    CompositeType "pg_stat_bgwriter",
    CompositeType "pg_stat_database",
    CompositeType "pg_statio_all_indexes",
    CompositeType "pg_statio_all_sequences",
    CompositeType "pg_statio_all_tables",
    CompositeType "pg_statio_sys_indexes",
    CompositeType "pg_statio_sys_sequences",
    CompositeType "pg_statio_sys_tables",
    CompositeType "pg_statio_user_indexes",
    CompositeType "pg_statio_user_sequences",
    CompositeType "pg_statio_user_tables",
    CompositeType "pg_statistic",
    CompositeType "pg_stats",
    CompositeType "pg_stat_sys_indexes",
    CompositeType "pg_stat_sys_tables",
    CompositeType "pg_stat_user_functions",
    CompositeType "pg_stat_user_indexes",
    CompositeType "pg_stat_user_tables",
    CompositeType "pg_tables",
    CompositeType "pg_tablespace",
    CompositeType "pg_timezone_abbrevs",
    CompositeType "pg_timezone_names",
    CompositeType "pg_trigger",
    CompositeType "pg_ts_config",
    CompositeType "pg_ts_config_map",
    CompositeType "pg_ts_dict",
    CompositeType "pg_ts_parser",
    CompositeType "pg_ts_template",
    CompositeType "pg_type",
    CompositeType "pg_user",
    CompositeType "pg_user_mapping",
    CompositeType "pg_user_mappings",
    CompositeType "pg_views",
    Pseudo Any,
    Pseudo AnyArray,
    Pseudo AnyElement,
    Pseudo AnyEnum,
    Pseudo AnyNonArray,
    Pseudo Cstring,
    Pseudo Internal,
    Pseudo LanguageHandler,
    Pseudo Opaque,
    Pseudo Record,
    Pseudo Trigger,
    Pseudo Void,
    ScalarType "abstime",
    ScalarType "aclitem",
    ScalarType "bit",
    ScalarType "bool",
    ScalarType "box",
    ScalarType "bpchar",
    ScalarType "bytea",
    ScalarType "char",
    ScalarType "cid",
    ScalarType "cidr",
    ScalarType "circle",
    ScalarType "date",
    ScalarType "float4",
    ScalarType "float8",
    ScalarType "gtsvector",
    ScalarType "inet",
    ScalarType "int2",
    ScalarType "int2vector",
    ScalarType "int4",
    ScalarType "int8",
    ScalarType "interval",
    ScalarType "line",
    ScalarType "lseg",
    ScalarType "macaddr",
    ScalarType "money",
    ScalarType "name",
    ScalarType "numeric",
    ScalarType "oid",
    ScalarType "oidvector",
    ScalarType "path",
    ScalarType "point",
    ScalarType "polygon",
    ScalarType "refcursor",
    ScalarType "regclass",
    ScalarType "regconfig",
    ScalarType "regdictionary",
    ScalarType "regoper",
    ScalarType "regoperator",
    ScalarType "regproc",
    ScalarType "regprocedure",
    ScalarType "regtype",
    ScalarType "reltime",
    ScalarType "smgr",
    ScalarType "text",
    ScalarType "tid",
    ScalarType "time",
    ScalarType "timestamp",
    ScalarType "timestamptz",
    ScalarType "timetz",
    ScalarType "tinterval",
    ScalarType "tsquery",
    ScalarType "tsvector",
    ScalarType "txid_snapshot",
    ScalarType "unknown",
    ScalarType "uuid",
    ScalarType "varbit",
    ScalarType "varchar",
    ScalarType "xid",
    ScalarType "xml"]
castTable :: [(Type, Type, CastContext)]
castTable = [
    (ScalarType "int8",ScalarType "int2",AssignmentCastContext),
    (ScalarType "int8",ScalarType "int4",AssignmentCastContext),
    (ScalarType "int8",ScalarType "float4",ImplicitCastContext),
    (ScalarType "int8",ScalarType "float8",ImplicitCastContext),
    (ScalarType "int8",ScalarType "numeric",ImplicitCastContext),
    (ScalarType "int2",ScalarType "int8",ImplicitCastContext),
    (ScalarType "int2",ScalarType "int4",ImplicitCastContext),
    (ScalarType "int2",ScalarType "float4",ImplicitCastContext),
    (ScalarType "int2",ScalarType "float8",ImplicitCastContext),
    (ScalarType "int2",ScalarType "numeric",ImplicitCastContext),
    (ScalarType "int4",ScalarType "int8",ImplicitCastContext),
    (ScalarType "int4",ScalarType "int2",AssignmentCastContext),
    (ScalarType "int4",ScalarType "float4",ImplicitCastContext),
    (ScalarType "int4",ScalarType "float8",ImplicitCastContext),
    (ScalarType "int4",ScalarType "numeric",ImplicitCastContext),
    (ScalarType "float4",ScalarType "int8",AssignmentCastContext),
    (ScalarType "float4",ScalarType "int2",AssignmentCastContext),
    (ScalarType "float4",ScalarType "int4",AssignmentCastContext),
    (ScalarType "float4",ScalarType "float8",ImplicitCastContext),
    (ScalarType "float4",ScalarType "numeric",AssignmentCastContext),
    (ScalarType "float8",ScalarType "int8",AssignmentCastContext),
    (ScalarType "float8",ScalarType "int2",AssignmentCastContext),
    (ScalarType "float8",ScalarType "int4",AssignmentCastContext),
    (ScalarType "float8",ScalarType "float4",AssignmentCastContext),
    (ScalarType "float8",ScalarType "numeric",AssignmentCastContext),
    (ScalarType "numeric",ScalarType "int8",AssignmentCastContext),
    (ScalarType "numeric",ScalarType "int2",AssignmentCastContext),
    (ScalarType "numeric",ScalarType "int4",AssignmentCastContext),
    (ScalarType "numeric",ScalarType "float4",ImplicitCastContext),
    (ScalarType "numeric",ScalarType "float8",ImplicitCastContext),
    (ScalarType "int4",ScalarType "bool",ExplicitCastContext),
    (ScalarType "bool",ScalarType "int4",ExplicitCastContext),
    (ScalarType "int8",ScalarType "oid",ImplicitCastContext),
    (ScalarType "int2",ScalarType "oid",ImplicitCastContext),
    (ScalarType "int4",ScalarType "oid",ImplicitCastContext),
    (ScalarType "oid",ScalarType "int8",AssignmentCastContext),
    (ScalarType "oid",ScalarType "int4",AssignmentCastContext),
    (ScalarType "oid",ScalarType "regproc",ImplicitCastContext),
    (ScalarType "regproc",ScalarType "oid",ImplicitCastContext),
    (ScalarType "int8",ScalarType "regproc",ImplicitCastContext),
    (ScalarType "int2",ScalarType "regproc",ImplicitCastContext),
    (ScalarType "int4",ScalarType "regproc",ImplicitCastContext),
    (ScalarType "regproc",ScalarType "int8",AssignmentCastContext),
    (ScalarType "regproc",ScalarType "int4",AssignmentCastContext),
    (ScalarType "regproc",ScalarType "regprocedure",ImplicitCastContext),
    (ScalarType "regprocedure",ScalarType "regproc",ImplicitCastContext),
    (ScalarType "oid",ScalarType "regprocedure",ImplicitCastContext),
    (ScalarType "regprocedure",ScalarType "oid",ImplicitCastContext),
    (ScalarType "int8",ScalarType "regprocedure",ImplicitCastContext),
    (ScalarType "int2",ScalarType "regprocedure",ImplicitCastContext),
    (ScalarType "int4",ScalarType "regprocedure",ImplicitCastContext),
    (ScalarType "regprocedure",ScalarType "int8",AssignmentCastContext),
    (ScalarType "regprocedure",ScalarType "int4",AssignmentCastContext),
    (ScalarType "oid",ScalarType "regoper",ImplicitCastContext),
    (ScalarType "regoper",ScalarType "oid",ImplicitCastContext),
    (ScalarType "int8",ScalarType "regoper",ImplicitCastContext),
    (ScalarType "int2",ScalarType "regoper",ImplicitCastContext),
    (ScalarType "int4",ScalarType "regoper",ImplicitCastContext),
    (ScalarType "regoper",ScalarType "int8",AssignmentCastContext),
    (ScalarType "regoper",ScalarType "int4",AssignmentCastContext),
    (ScalarType "regoper",ScalarType "regoperator",ImplicitCastContext),
    (ScalarType "regoperator",ScalarType "regoper",ImplicitCastContext),
    (ScalarType "oid",ScalarType "regoperator",ImplicitCastContext),
    (ScalarType "regoperator",ScalarType "oid",ImplicitCastContext),
    (ScalarType "int8",ScalarType "regoperator",ImplicitCastContext),
    (ScalarType "int2",ScalarType "regoperator",ImplicitCastContext),
    (ScalarType "int4",ScalarType "regoperator",ImplicitCastContext),
    (ScalarType "regoperator",ScalarType "int8",AssignmentCastContext),
    (ScalarType "regoperator",ScalarType "int4",AssignmentCastContext),
    (ScalarType "oid",ScalarType "regclass",ImplicitCastContext),
    (ScalarType "regclass",ScalarType "oid",ImplicitCastContext),
    (ScalarType "int8",ScalarType "regclass",ImplicitCastContext),
    (ScalarType "int2",ScalarType "regclass",ImplicitCastContext),
    (ScalarType "int4",ScalarType "regclass",ImplicitCastContext),
    (ScalarType "regclass",ScalarType "int8",AssignmentCastContext),
    (ScalarType "regclass",ScalarType "int4",AssignmentCastContext),
    (ScalarType "oid",ScalarType "regtype",ImplicitCastContext),
    (ScalarType "regtype",ScalarType "oid",ImplicitCastContext),
    (ScalarType "int8",ScalarType "regtype",ImplicitCastContext),
    (ScalarType "int2",ScalarType "regtype",ImplicitCastContext),
    (ScalarType "int4",ScalarType "regtype",ImplicitCastContext),
    (ScalarType "regtype",ScalarType "int8",AssignmentCastContext),
    (ScalarType "regtype",ScalarType "int4",AssignmentCastContext),
    (ScalarType "oid",ScalarType "regconfig",ImplicitCastContext),
    (ScalarType "regconfig",ScalarType "oid",ImplicitCastContext),
    (ScalarType "int8",ScalarType "regconfig",ImplicitCastContext),
    (ScalarType "int2",ScalarType "regconfig",ImplicitCastContext),
    (ScalarType "int4",ScalarType "regconfig",ImplicitCastContext),
    (ScalarType "regconfig",ScalarType "int8",AssignmentCastContext),
    (ScalarType "regconfig",ScalarType "int4",AssignmentCastContext),
    (ScalarType "oid",ScalarType "regdictionary",ImplicitCastContext),
    (ScalarType "regdictionary",ScalarType "oid",ImplicitCastContext),
    (ScalarType "int8",ScalarType "regdictionary",ImplicitCastContext),
    (ScalarType "int2",ScalarType "regdictionary",ImplicitCastContext),
    (ScalarType "int4",ScalarType "regdictionary",ImplicitCastContext),
    (ScalarType "regdictionary",ScalarType "int8",AssignmentCastContext),
    (ScalarType "regdictionary",ScalarType "int4",AssignmentCastContext),
    (ScalarType "text",ScalarType "regclass",ImplicitCastContext),
    (ScalarType "varchar",ScalarType "regclass",ImplicitCastContext),
    (ScalarType "text",ScalarType "bpchar",ImplicitCastContext),
    (ScalarType "text",ScalarType "varchar",ImplicitCastContext),
    (ScalarType "bpchar",ScalarType "text",ImplicitCastContext),
    (ScalarType "bpchar",ScalarType "varchar",ImplicitCastContext),
    (ScalarType "varchar",ScalarType "text",ImplicitCastContext),
    (ScalarType "varchar",ScalarType "bpchar",ImplicitCastContext),
    (ScalarType "char",ScalarType "text",ImplicitCastContext),
    (ScalarType "char",ScalarType "bpchar",AssignmentCastContext),
    (ScalarType "char",ScalarType "varchar",AssignmentCastContext),
    (ScalarType "name",ScalarType "text",ImplicitCastContext),
    (ScalarType "name",ScalarType "bpchar",AssignmentCastContext),
    (ScalarType "name",ScalarType "varchar",AssignmentCastContext),
    (ScalarType "text",ScalarType "char",AssignmentCastContext),
    (ScalarType "bpchar",ScalarType "char",AssignmentCastContext),
    (ScalarType "varchar",ScalarType "char",AssignmentCastContext),
    (ScalarType "text",ScalarType "name",ImplicitCastContext),
    (ScalarType "bpchar",ScalarType "name",ImplicitCastContext),
    (ScalarType "varchar",ScalarType "name",ImplicitCastContext),
    (ScalarType "char",ScalarType "int4",ExplicitCastContext),
    (ScalarType "int4",ScalarType "char",ExplicitCastContext),
    (ScalarType "abstime",ScalarType "date",AssignmentCastContext),
    (ScalarType "abstime",ScalarType "time",AssignmentCastContext),
    (ScalarType "abstime",ScalarType "timestamp",ImplicitCastContext),
    (ScalarType "abstime",ScalarType "timestamptz",ImplicitCastContext),
    (ScalarType "reltime",ScalarType "interval",ImplicitCastContext),
    (ScalarType "date",ScalarType "timestamp",ImplicitCastContext),
    (ScalarType "date",ScalarType "timestamptz",ImplicitCastContext),
    (ScalarType "time",ScalarType "interval",ImplicitCastContext),
    (ScalarType "time",ScalarType "timetz",ImplicitCastContext),
    (ScalarType "timestamp",ScalarType "abstime",AssignmentCastContext),
    (ScalarType "timestamp",ScalarType "date",AssignmentCastContext),
    (ScalarType "timestamp",ScalarType "time",AssignmentCastContext),
    (ScalarType "timestamp",ScalarType "timestamptz",ImplicitCastContext),
    (ScalarType "timestamptz",ScalarType "abstime",AssignmentCastContext),
    (ScalarType "timestamptz",ScalarType "date",AssignmentCastContext),
    (ScalarType "timestamptz",ScalarType "time",AssignmentCastContext),
    (ScalarType "timestamptz",ScalarType "timestamp",AssignmentCastContext),
    (ScalarType "timestamptz",ScalarType "timetz",AssignmentCastContext),
    (ScalarType "interval",ScalarType "reltime",AssignmentCastContext),
    (ScalarType "interval",ScalarType "time",AssignmentCastContext),
    (ScalarType "timetz",ScalarType "time",AssignmentCastContext),
    (ScalarType "int4",ScalarType "abstime",ExplicitCastContext),
    (ScalarType "abstime",ScalarType "int4",ExplicitCastContext),
    (ScalarType "int4",ScalarType "reltime",ExplicitCastContext),
    (ScalarType "reltime",ScalarType "int4",ExplicitCastContext),
    (ScalarType "lseg",ScalarType "point",ExplicitCastContext),
    (ScalarType "path",ScalarType "point",ExplicitCastContext),
    (ScalarType "path",ScalarType "polygon",AssignmentCastContext),
    (ScalarType "box",ScalarType "point",ExplicitCastContext),
    (ScalarType "box",ScalarType "lseg",ExplicitCastContext),
    (ScalarType "box",ScalarType "polygon",AssignmentCastContext),
    (ScalarType "box",ScalarType "circle",ExplicitCastContext),
    (ScalarType "polygon",ScalarType "point",ExplicitCastContext),
    (ScalarType "polygon",ScalarType "path",AssignmentCastContext),
    (ScalarType "polygon",ScalarType "box",ExplicitCastContext),
    (ScalarType "polygon",ScalarType "circle",ExplicitCastContext),
    (ScalarType "circle",ScalarType "point",ExplicitCastContext),
    (ScalarType "circle",ScalarType "box",ExplicitCastContext),
    (ScalarType "circle",ScalarType "polygon",ExplicitCastContext),
    (ScalarType "cidr",ScalarType "inet",ImplicitCastContext),
    (ScalarType "inet",ScalarType "cidr",AssignmentCastContext),
    (ScalarType "bit",ScalarType "varbit",ImplicitCastContext),
    (ScalarType "varbit",ScalarType "bit",ImplicitCastContext),
    (ScalarType "int8",ScalarType "bit",ExplicitCastContext),
    (ScalarType "int4",ScalarType "bit",ExplicitCastContext),
    (ScalarType "bit",ScalarType "int8",ExplicitCastContext),
    (ScalarType "bit",ScalarType "int4",ExplicitCastContext),
    (ScalarType "cidr",ScalarType "text",AssignmentCastContext),
    (ScalarType "inet",ScalarType "text",AssignmentCastContext),
    (ScalarType "bool",ScalarType "text",AssignmentCastContext),
    (ScalarType "xml",ScalarType "text",AssignmentCastContext),
    (ScalarType "text",ScalarType "xml",ExplicitCastContext),
    (ScalarType "cidr",ScalarType "varchar",AssignmentCastContext),
    (ScalarType "inet",ScalarType "varchar",AssignmentCastContext),
    (ScalarType "bool",ScalarType "varchar",AssignmentCastContext),
    (ScalarType "xml",ScalarType "varchar",AssignmentCastContext),
    (ScalarType "varchar",ScalarType "xml",ExplicitCastContext),
    (ScalarType "cidr",ScalarType "bpchar",AssignmentCastContext),
    (ScalarType "inet",ScalarType "bpchar",AssignmentCastContext),
    (ScalarType "bool",ScalarType "bpchar",AssignmentCastContext),
    (ScalarType "xml",ScalarType "bpchar",AssignmentCastContext),
    (ScalarType "bpchar",ScalarType "xml",ExplicitCastContext),
    (ScalarType "bpchar",ScalarType "bpchar",ImplicitCastContext),
    (ScalarType "varchar",ScalarType "varchar",ImplicitCastContext),
    (ScalarType "time",ScalarType "time",ImplicitCastContext),
    (ScalarType "timestamp",ScalarType "timestamp",ImplicitCastContext),
    (ScalarType "timestamptz",ScalarType "timestamptz",ImplicitCastContext),
    (ScalarType "interval",ScalarType "interval",ImplicitCastContext),
    (ScalarType "timetz",ScalarType "timetz",ImplicitCastContext),
    (ScalarType "bit",ScalarType "bit",ImplicitCastContext),
    (ScalarType "varbit",ScalarType "varbit",ImplicitCastContext),
    (ScalarType "numeric",ScalarType "numeric",ImplicitCastContext)]
typeCategories :: [(Type, [Char], Bool)]
typeCategories = [
    (ArrayType (Pseudo Cstring), "A", False),
    (ArrayType (ScalarType "abstime"), "A", False),
    (ArrayType (ScalarType "aclitem"), "A", False),
    (ArrayType (ScalarType "bit"), "A", False),
    (ArrayType (ScalarType "bool"), "A", False),
    (ArrayType (ScalarType "box"), "A", False),
    (ArrayType (ScalarType "bpchar"), "A", False),
    (ArrayType (ScalarType "bytea"), "A", False),
    (ArrayType (ScalarType "char"), "A", False),
    (ArrayType (ScalarType "cid"), "A", False),
    (ArrayType (ScalarType "cidr"), "A", False),
    (ArrayType (ScalarType "circle"), "A", False),
    (ArrayType (ScalarType "date"), "A", False),
    (ArrayType (ScalarType "float4"), "A", False),
    (ArrayType (ScalarType "float8"), "A", False),
    (ArrayType (ScalarType "gtsvector"), "A", False),
    (ArrayType (ScalarType "inet"), "A", False),
    (ArrayType (ScalarType "int2"), "A", False),
    (ArrayType (ScalarType "int2vector"), "A", False),
    (ArrayType (ScalarType "int4"), "A", False),
    (ArrayType (ScalarType "int8"), "A", False),
    (ArrayType (ScalarType "interval"), "A", False),
    (ArrayType (ScalarType "line"), "A", False),
    (ArrayType (ScalarType "lseg"), "A", False),
    (ArrayType (ScalarType "macaddr"), "A", False),
    (ArrayType (ScalarType "money"), "A", False),
    (ArrayType (ScalarType "name"), "A", False),
    (ArrayType (ScalarType "numeric"), "A", False),
    (ArrayType (ScalarType "oid"), "A", False),
    (ArrayType (ScalarType "oidvector"), "A", False),
    (ArrayType (ScalarType "path"), "A", False),
    (ArrayType (ScalarType "point"), "A", False),
    (ArrayType (ScalarType "polygon"), "A", False),
    (ArrayType (ScalarType "refcursor"), "A", False),
    (ArrayType (ScalarType "regclass"), "A", False),
    (ArrayType (ScalarType "regconfig"), "A", False),
    (ArrayType (ScalarType "regdictionary"), "A", False),
    (ArrayType (ScalarType "regoper"), "A", False),
    (ArrayType (ScalarType "regoperator"), "A", False),
    (ArrayType (ScalarType "regproc"), "A", False),
    (ArrayType (ScalarType "regprocedure"), "A", False),
    (ArrayType (ScalarType "regtype"), "A", False),
    (ArrayType (ScalarType "reltime"), "A", False),
    (ArrayType (ScalarType "text"), "A", False),
    (ArrayType (ScalarType "tid"), "A", False),
    (ArrayType (ScalarType "time"), "A", False),
    (ArrayType (ScalarType "timestamp"), "A", False),
    (ArrayType (ScalarType "timestamptz"), "A", False),
    (ArrayType (ScalarType "timetz"), "A", False),
    (ArrayType (ScalarType "tinterval"), "A", False),
    (ArrayType (ScalarType "tsquery"), "A", False),
    (ArrayType (ScalarType "tsvector"), "A", False),
    (ArrayType (ScalarType "txid_snapshot"), "A", False),
    (ArrayType (ScalarType "uuid"), "A", False),
    (ArrayType (ScalarType "varbit"), "A", False),
    (ArrayType (ScalarType "varchar"), "A", False),
    (ArrayType (ScalarType "xid"), "A", False),
    (ArrayType (ScalarType "xml"), "A", False),
    (ScalarType "int2vector", "A", False),
    (ScalarType "oidvector", "A", False),
    (ScalarType "bool", "B", True),
    (CompositeType "pg_aggregate", "C", False),
    (CompositeType "pg_am", "C", False),
    (CompositeType "pg_amop", "C", False),
    (CompositeType "pg_amproc", "C", False),
    (CompositeType "pg_attrdef", "C", False),
    (CompositeType "pg_attribute", "C", False),
    (CompositeType "pg_authid", "C", False),
    (CompositeType "pg_auth_members", "C", False),
    (CompositeType "pg_cast", "C", False),
    (CompositeType "pg_class", "C", False),
    (CompositeType "pg_constraint", "C", False),
    (CompositeType "pg_conversion", "C", False),
    (CompositeType "pg_cursors", "C", False),
    (CompositeType "pg_database", "C", False),
    (CompositeType "pg_depend", "C", False),
    (CompositeType "pg_description", "C", False),
    (CompositeType "pg_enum", "C", False),
    (CompositeType "pg_foreign_data_wrapper", "C", False),
    (CompositeType "pg_foreign_server", "C", False),
    (CompositeType "pg_group", "C", False),
    (CompositeType "pg_index", "C", False),
    (CompositeType "pg_indexes", "C", False),
    (CompositeType "pg_inherits", "C", False),
    (CompositeType "pg_language", "C", False),
    (CompositeType "pg_largeobject", "C", False),
    (CompositeType "pg_listener", "C", False),
    (CompositeType "pg_locks", "C", False),
    (CompositeType "pg_namespace", "C", False),
    (CompositeType "pg_opclass", "C", False),
    (CompositeType "pg_operator", "C", False),
    (CompositeType "pg_opfamily", "C", False),
    (CompositeType "pg_pltemplate", "C", False),
    (CompositeType "pg_prepared_statements", "C", False),
    (CompositeType "pg_prepared_xacts", "C", False),
    (CompositeType "pg_proc", "C", False),
    (CompositeType "pg_rewrite", "C", False),
    (CompositeType "pg_roles", "C", False),
    (CompositeType "pg_rules", "C", False),
    (CompositeType "pg_settings", "C", False),
    (CompositeType "pg_shadow", "C", False),
    (CompositeType "pg_shdepend", "C", False),
    (CompositeType "pg_shdescription", "C", False),
    (CompositeType "pg_stat_activity", "C", False),
    (CompositeType "pg_stat_all_indexes", "C", False),
    (CompositeType "pg_stat_all_tables", "C", False),
    (CompositeType "pg_stat_bgwriter", "C", False),
    (CompositeType "pg_stat_database", "C", False),
    (CompositeType "pg_statio_all_indexes", "C", False),
    (CompositeType "pg_statio_all_sequences", "C", False),
    (CompositeType "pg_statio_all_tables", "C", False),
    (CompositeType "pg_statio_sys_indexes", "C", False),
    (CompositeType "pg_statio_sys_sequences", "C", False),
    (CompositeType "pg_statio_sys_tables", "C", False),
    (CompositeType "pg_statio_user_indexes", "C", False),
    (CompositeType "pg_statio_user_sequences", "C", False),
    (CompositeType "pg_statio_user_tables", "C", False),
    (CompositeType "pg_statistic", "C", False),
    (CompositeType "pg_stats", "C", False),
    (CompositeType "pg_stat_sys_indexes", "C", False),
    (CompositeType "pg_stat_sys_tables", "C", False),
    (CompositeType "pg_stat_user_functions", "C", False),
    (CompositeType "pg_stat_user_indexes", "C", False),
    (CompositeType "pg_stat_user_tables", "C", False),
    (CompositeType "pg_tables", "C", False),
    (CompositeType "pg_tablespace", "C", False),
    (CompositeType "pg_timezone_abbrevs", "C", False),
    (CompositeType "pg_timezone_names", "C", False),
    (CompositeType "pg_trigger", "C", False),
    (CompositeType "pg_ts_config", "C", False),
    (CompositeType "pg_ts_config_map", "C", False),
    (CompositeType "pg_ts_dict", "C", False),
    (CompositeType "pg_ts_parser", "C", False),
    (CompositeType "pg_ts_template", "C", False),
    (CompositeType "pg_type", "C", False),
    (CompositeType "pg_user", "C", False),
    (CompositeType "pg_user_mapping", "C", False),
    (CompositeType "pg_user_mappings", "C", False),
    (CompositeType "pg_views", "C", False),
    (ScalarType "timestamptz", "D", True),
    (ScalarType "abstime", "D", False),
    (ScalarType "date", "D", False),
    (ScalarType "time", "D", False),
    (ScalarType "timestamp", "D", False),
    (ScalarType "timetz", "D", False),
    (ScalarType "box", "G", False),
    (ScalarType "circle", "G", False),
    (ScalarType "line", "G", False),
    (ScalarType "lseg", "G", False),
    (ScalarType "path", "G", False),
    (ScalarType "point", "G", False),
    (ScalarType "polygon", "G", False),
    (ScalarType "inet", "I", True),
    (ScalarType "cidr", "I", False),
    (ScalarType "float8", "N", True),
    (ScalarType "oid", "N", True),
    (ScalarType "float4", "N", False),
    (ScalarType "int2", "N", False),
    (ScalarType "int4", "N", False),
    (ScalarType "int8", "N", False),
    (ScalarType "money", "N", False),
    (ScalarType "numeric", "N", False),
    (ScalarType "regclass", "N", False),
    (ScalarType "regconfig", "N", False),
    (ScalarType "regdictionary", "N", False),
    (ScalarType "regoper", "N", False),
    (ScalarType "regoperator", "N", False),
    (ScalarType "regproc", "N", False),
    (ScalarType "regprocedure", "N", False),
    (ScalarType "regtype", "N", False),
    (ArrayType (Pseudo Record), "P", False),
    (Pseudo Any, "P", False),
    (Pseudo AnyArray, "P", False),
    (Pseudo AnyElement, "P", False),
    (Pseudo AnyEnum, "P", False),
    (Pseudo AnyNonArray, "P", False),
    (Pseudo Cstring, "P", False),
    (Pseudo Internal, "P", False),
    (Pseudo LanguageHandler, "P", False),
    (Pseudo Opaque, "P", False),
    (Pseudo Record, "P", False),
    (Pseudo Trigger, "P", False),
    (Pseudo Void, "P", False),
    (ScalarType "text", "S", True),
    (ScalarType "bpchar", "S", False),
    (ScalarType "char", "S", False),
    (ScalarType "name", "S", False),
    (ScalarType "varchar", "S", False),
    (ScalarType "interval", "T", True),
    (ScalarType "reltime", "T", False),
    (ScalarType "tinterval", "T", False),
    (ScalarType "aclitem", "U", False),
    (ScalarType "bytea", "U", False),
    (ScalarType "cid", "U", False),
    (ScalarType "gtsvector", "U", False),
    (ScalarType "macaddr", "U", False),
    (ScalarType "refcursor", "U", False),
    (ScalarType "smgr", "U", False),
    (ScalarType "tid", "U", False),
    (ScalarType "tsquery", "U", False),
    (ScalarType "tsvector", "U", False),
    (ScalarType "txid_snapshot", "U", False),
    (ScalarType "uuid", "U", False),
    (ScalarType "xid", "U", False),
    (ScalarType "xml", "U", False),
    (ScalarType "varbit", "V", True),
    (ScalarType "bit", "V", False),
    (ScalarType "unknown", "X", False)]
